# Generated by Django 6.0.6 on 2026-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(choices=[('Diploma', 'Diploma'), ('ITI', 'ITI')], max_length=20)),
                ('branch', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Computer', 'Computer'), ('CNC Operator', 'CNC Operator'), ('Fitter', 'Fitter'), ('Turner', 'Turner'), ('Welder', 'Welder'), ('Machinist', 'Machinist'), ('Automobile', 'Automobile')], max_length=50)),
                ('college', models.CharField(max_length=150)),
                ('passing_year', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 Year', '0-1 Year'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('5+ Years', '5+ Years')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
